# Generated by Django 4.2.2 on 2023-07-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeditem',
            name='content_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likeditem',
            name='object_id',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
