# Generated by Django 4.2.2 on 2023-07-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0002_likeditem_content_type_likeditem_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeditem',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
